[project]
name = "robo-cestinha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
    "nba-api>=1.11.4",
    "pandas>=3.0.5",
    "polars>=1.44.2",
    "pydantic>=2.9",
    "pyarrow>=25.0.1",
]
